# Generated by Django 5.2.1 on 2025-05-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_commented', 'Task Commented'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_member_added', 'Project Member Added'), ('chat_message', 'Chat Message'), ('system', 'System Notification')], default='system', max_length=50),
        ),
    ]
